language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"

jobs:
  include:
    - stage: cover
      node_js: "stable"
      script:
        - npm run cover
    - stage: npm release
      node_js: "stable"
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: vs@lutov.net
        on:
          tags: true
